### ISSUE TITLE
Cannot find module 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by dankantor** [dfrankland/zerocater-node#2]
Just followed the instructions, ran it and got this error -

```
Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/dankantor/work/slack-slash-commands/node_modules/zerocater/lib/index.js:7:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)```

**Comment by dfrankland** [comment]
Ah, I know how to fix this. I'll get on it soon 👍

**Comment by dfrankland** [comment]
Hello! Do you mind checking out version `1.1.0`? I think everything should be fixed with that version now 🦄

**Comment by dankantor** [comment]
Just updated. Thanks for the quick fix! Unfortunatelly I'm getting this error now - 

```
var ZeroCater = require('zerocater').default;
const zc = ZeroCater('XXXXX');
```
```
TypeError: ZeroCater is not a function
    at Object.<anonymous> (/Users/dankantor/work/slack-slash-commands/lib/zerocater.js:3:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/dankantor/work/slack-slash-commands/index.js:8:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

**Comment by dfrankland** [comment]
Gotcha. I switched over to `rollup` which allows both ES5 and ES6 to work without the `default` property. I just updated the `README.md` to reflect this. It's not necessary to update, just remove `default` like below:

```js
var ZeroCater = require('zerocater');
const zc = ZeroCater('XXXXX');
```

**Comment by dfrankland** [comment]
Closing due to age; feel free to re-open.
